package com.lib;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

@SpringBootApplication
public class Library {
	
	public static void main(String[] args) {
		SpringApplication.run(Library.class, args);
	}
  
}
